apiVersion: v1
kind: Service
metadata:
  name: kafka-bootstrap
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  ports:
  - port: 9092
  clusterIP: None
  selector:
    app: kafka

