apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashtag2mysql
spec:
  selector:
    matchLabels:
      app: hashtag2mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hashtag2mysql
    spec:
      containers:
        - name: hashtag2mysql
          image: "mariadb:10.3"
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.5"
            requests:
              memory: "200Mi"
              cpu: "0.2"
